### ISSUE TITLE
Finding error

### ISSUE THREAD

**Issue by richardminh** [faezetta/VMMRdb#2]
Dear, faezetta. How are you?
I am gonna train vehicle make and model recognition application with deep learning. I tried with stanford dataset but i couldn't enough performance. I read the University of Louisville ' paper "Vehicle make and model recognition for intelligent
transportation monitoring and surveillance"  and thought this dataset is very good for vmmr but i couldn't see anything in http://vmmrdb.cecsresearch.org/.
Would you let me know full url for downloading dataset?
Kind regards.
Thanks.

**Comment by faezetta** [comment]
@richardminh thanks for your interest in the dataset. Seems like the server is down temporarily...in the meantime you can download the dataset from [here](https://www.dropbox.com/s/uwa7c5uz7cac7cw/VMMRdb.zip?dl=0). Let me know if you have any issues accessing the file.

**Comment by richardminh** [comment]
Thanks very much.. Let me download ..
