### ISSUE TITLE
Download link do not work

### ISSUE THREAD

**Issue by matvils** [faezetta/VMMRdb#4]
As mentioned in title, download link do not work anymore. Is there possibility to fix that?

**Comment by faezetta** [comment]
Hello @matvils - looks like the server is down, I'll follow up on that. In the meantime you can use the following link to download the dataset: https://www.dropbox.com/s/uwa7c5uz7cac7cw/VMMRdb.zip?dl=0
Let me know if you have any issues accessing the content.

**Comment by matvils** [comment]
Hello!
Thanks! I am downloading drom dropbox right now.
I am working with europe car dataset (scraping is going to end this week), if you are interested, i can share it.

**Comment by faezetta** [comment]
Nice! Sure, I would definitely be interested.

**Comment by baselmousi** [comment]
Hello! @matvils  may you please share with me the europe car dataset too? 
Thanks in advance!

**Comment by matvils** [comment]
Can I close issue?
p.s. my eu car dataset:
https://github.com/matvils/EVmmdb

**Comment by faezetta** [comment]
Thanks for sharing your dataset @matvils

**Comment by saifedin6** [comment]
Hello, Can you tell me please how to find the train.csv and test.csv files ? I can't find them in this dataset thanks
